version: '3'
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - "9906:3306"
  web:
    build: ./web
    container_name: webtest
    depends_on:
      - db
    ports:
      - "9999:80"
    volumes:
      - ./web/src:/var/www/html
    stdin_open: true
    tty: true
